modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="obliterum"
version="1.0.0"
displayName="Obliterum"
credits="Cobalt for any textures other than default mcreator textures."
displayURL="https://mcreator.net"
authors="Raeis_Eikr, Cobalt"
description='''
Custom mod created for use with Obliterum server. WIP
'''

[[dependencies.obliterum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




